テキスト中からurlと謎文字を削除（remove_urljとremove_strange)ブランチ再設定
GENIAC-Team-Ozaki/oss-llm-japanese pull request #29
Opened 2024-04-07 17:05 UTC by TosNishida

- remove_urlj
    - http:などのurlを削除、ftp: や日本語を含む場合も対応。
    - 周囲の（）等は残ります。

- remove_strange
    - 謎文字を削除（通常の日本語話者が意味を読み取れるものは残している）

2024-04-08 04:43 UTC, takeshun256 requested changes

2024-04-08 04:43 UTC, takeshun256 commented on src/preprocessing/scripts/filter_data.py
> +        filter_fns.append(remove_strange())
関数の種類について1点修正をお願いします！
というのも、URLの削除と謎文字の削除は、どちらも文章を落とす(filter処理)というよりは文章を改変する(map処理)のためです。
```suggestion
        map_fns.append(remove_urlj())
        map_fns.append(remove_strange())
```

2024-04-08 04:43 UTC, takeshun256 commented on src/preprocessing/scripts/filters.py
> +        example["text"] = remove_strange.sub("", example["text"])
謎文字削除の実装について、2点確認です。

① 謎文字の正規表現について、[こちらのCommonCrawlの正規化](https://www.notion.so/matsuolab-geniac/088e5191e643429ca08dfe628f66ce69?pvs=4#e411ad32dcdc478dba0497fd4e3f610d) の方はご確認されているしょうか？ただし、おそらく上記リンクに載っている処理は英語用のためそのままでは使用できないと思います. 
② @TosNishida さんの実装された以下の処理はどこの処理を参考にされたでしょうか？

```python
        strange_pat = (
            r"[^\p{Script=Latin}\p{Number}\p{Punctuation}\p{Symbol}"
            r"\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Han}]"
        )
```

以上2点、念の為確認させてください！

2024-04-08 05:53 UTC, takeshun256 commented on src/preprocessing/scripts/filter_data.py
> +        filter_fns.append(remove_strange())
[c596576](https://github.com/GENIAC-Team-Ozaki/oss-llm-japanese/pull/29/commits/c596576aa954978e1396111fdee45ba38c4a37d3) で修正済み

2024-04-08 11:01 UTC, TosNishida commented on src/preprocessing/scripts/filters.py
> +        example["text"] = remove_strange.sub("", example["text"])
Bing Copilotやその他ネット上で調べた正規表現を参考にして、extract_japanese_textの構成を参考に作成いたしました。前回のPRではカバーできていなかった正規表現を再調査でカバーし、見やすいコードにしました。

2024-04-09 11:21 UTC, takeshun256 approved these changes

2024-04-09 13:55 UTC, takeshun256 commented
URLの削除と、謎文字の削除(文字化けなども削除)について、把握しました。
LGTMです！

2024-04-09 13:56 UTC, merged